#ifndef VISAO_COMPUTACIONAL_GLOBAL_H
#define VISAO_COMPUTACIONAL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(VISAO_COMPUTACIONAL_LIBRARY)
#  define VISAO_COMPUTACIONALSHARED_EXPORT Q_DECL_EXPORT
#else
#  define VISAO_COMPUTACIONALSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // VISAO_COMPUTACIONAL_GLOBAL_H
